"""Bounded interpreter for the SDK policy language (a Python syntax subset).

This is not a sandbox for arbitrary Python. Generated bytecode, exec/eval, host
imports, arbitrary attributes, host callbacks, files, network and processes are unavailable.
Limits bound source, AST, operations and cumulative value size, not OS RSS.
"""

from __future__ import annotations

import ast
import hashlib
import math
import operator
import time
from dataclasses import asdict, dataclass, replace
from typing import Any

from dreamrsi.errors import SandboxError
from dreamrsi.models.policy import PolicyDecision

_BINARY = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.FloorDiv: operator.floordiv,
    ast.Mod: operator.mod,
}
_COMPARE = {
    ast.Eq: operator.eq,
    ast.NotEq: operator.ne,
    ast.Lt: operator.lt,
    ast.LtE: operator.le,
    ast.Gt: operator.gt,
    ast.GtE: operator.ge,
    ast.Is: operator.is_,
    ast.IsNot: operator.is_not,
    ast.In: lambda a, b: a in b,
    ast.NotIn: lambda a, b: a not in b,
}
_ALLOWED = (
    ast.Module,
    ast.FunctionDef,
    ast.arguments,
    ast.arg,
    ast.Return,
    ast.Assign,
    ast.AugAssign,
    ast.Tuple,
    ast.ListComp,
    ast.DictComp,
    ast.GeneratorExp,
    ast.comprehension,
    ast.Attribute,
    ast.keyword,
    ast.Lambda,
    ast.Import,
    ast.alias,
    ast.If,
    ast.For,
    ast.While,
    ast.Break,
    ast.Continue,
    ast.Pass,
    ast.Expr,
    ast.Name,
    ast.Load,
    ast.Store,
    ast.Constant,
    ast.List,
    ast.Dict,
    ast.Subscript,
    ast.Slice,
    ast.BinOp,
    ast.UnaryOp,
    ast.BoolOp,
    ast.Compare,
    ast.IfExp,
    ast.Call,
    ast.And,
    ast.Or,
    ast.Not,
    ast.USub,
    ast.UAdd,
    *_BINARY.keys(),
    *_COMPARE.keys(),
)
_FUNCTIONS = {
    "len",
    "min",
    "max",
    "sum",
    "abs",
    "range",
    "get",
    "sorted",
    "enumerate",
    "zip",
    "list",
    "dict",
    "reversed",
    "all",
    "any",
    "round",
    "int",
    "float",
    "bool",
    "str",
}
_MATH = {
    name: getattr(math, name)
    for name in ("sqrt", "log", "log2", "log10", "exp", "sin", "cos", "tanh", "floor", "ceil")
}
_METHODS = {
    dict: {"get", "keys", "values", "items", "copy"},
    list: {"append", "extend", "pop", "count", "index", "copy", "sort"},
    str: {"lower", "upper", "startswith", "endswith", "strip"},
}
_METHOD_NAMES = {f"{kind.__name__}.{name}" for kind, names in _METHODS.items() for name in names}
_MATH_NAMES = set(_MATH) | {"pi", "e", "tau"}


@dataclass(frozen=True)
class SandboxConfig:
    max_steps: int = 100000
    max_items: int = 20000
    max_units: int = 2000000
    max_source_bytes: int = 131072
    max_ast_nodes: int = 16000
    max_value_depth: int = 48
    max_integer_bits: int = 512
    max_call_depth: int = 32
    allow_helpers: bool = True
    allow_comprehensions: bool = True
    allow_methods: bool = True
    allow_math: bool = True
    allowed_builtins: tuple[str, ...] | None = None
    allowed_math: tuple[str, ...] | None = None
    allowed_methods: tuple[str, ...] | None = None

    def __post_init__(self):
        for name, value in asdict(self).items():
            if name.startswith("max_") and (type(value) is not int or value < 1):
                raise ValueError(f"{name} must be a positive integer")
            if name.startswith("allow_") and type(value) is not bool:
                raise ValueError(f"{name} must be boolean")
        for name, available in (
            ("allowed_builtins", _FUNCTIONS),
            ("allowed_math", _MATH_NAMES),
            ("allowed_methods", _METHOD_NAMES),
        ):
            value = getattr(self, name)
            if value is not None:
                if not isinstance(value, (tuple, list)) or any(
                    not isinstance(item, str) or item not in available for item in value
                ):
                    raise ValueError(f"{name} must contain only supported names")
                object.__setattr__(self, name, tuple(sorted(set(value))))

    def to_dict(self):
        return {
            key: list(value) if isinstance(value, tuple) else value
            for key, value in asdict(self).items()
        }

    @classmethod
    def from_dict(cls, data):
        return cls(**data)


class _Return(Exception):
    def __init__(self, value):
        self.value = value


class _Break(Exception):
    pass


class _Continue(Exception):
    pass


class PolicySandbox:
    """No dependencies. Each call gets a fresh interpreter and JSON-only view."""

    def __init__(self, config=None, **limits):
        self.config = replace(config or SandboxConfig(), **limits)
        for name, value in asdict(self.config).items():
            setattr(self, name, value)

    def capabilities(self):
        return {
            "language": "dreamrsi-policy-v4",
            "limits": self.config.to_dict(),
            "builtins": sorted(self.enabled_builtins),
            "syntax": [
                "functions",
                "if/else",
                "for/while",
                "return",
                "break/continue",
                "assignment",
                "augmented assignment",
                "list/dict comprehensions and eagerly materialized generator expressions",
                "JSON values",
                "tuple unpacking",
                "indexing/slicing",
                "arithmetic",
                "sorting with lambda/helper key",
                "collection methods",
                "import math",
            ],
            "math": sorted(self.enabled_math),
            "contract": {
                "entrypoint": "def decide(view): returns expand, stop, optional parallelism",
                "helpers": "Module or local named functions, recursion and captured local values",
                "imports": "Only import math (optionally as alias), module or function scope",
                "numbers": "Finite numbers only; handle None explicitly, no float('inf')",
                "lambdas": "Only one-argument sorting/selection keys",
                "state": "Fresh execution per decision; derive memory from view.history",
                "methods": {
                    kind.__name__: sorted(
                        name for name in names if f"{kind.__name__}.{name}" in self.enabled_methods
                    )
                    for kind, names in _METHODS.items()
                },
            },
            "forbidden": [
                "host imports except math proxy",
                "dunder attributes",
                "files",
                "network",
                "processes",
                "dynamic Python execution",
            ],
        }

    @property
    def enabled_builtins(self):
        return (
            _FUNCTIONS
            if self.config.allowed_builtins is None
            else set(self.config.allowed_builtins)
        )

    @property
    def enabled_math(self):
        if not self.config.allow_math:
            return set()
        return _MATH_NAMES if self.config.allowed_math is None else set(self.config.allowed_math)

    @property
    def enabled_methods(self):
        if not self.config.allow_methods:
            return set()
        return (
            _METHOD_NAMES
            if self.config.allowed_methods is None
            else set(self.config.allowed_methods)
        )

    def parse(self, code):
        if type(code) is not str or len(code.encode()) > self.config.max_source_bytes:
            raise SandboxError("Policy source limit exceeded")
        try:
            tree = ast.parse(code)
        except SyntaxError as exc:
            raise SandboxError(f"Line {exc.lineno}:{exc.offset}: {exc.msg}") from exc
        nodes = list(ast.walk(tree))
        if len(nodes) > self.config.max_ast_nodes:
            raise SandboxError("AST node limit exceeded")
        for node in nodes:
            reason = None
            if not isinstance(node, _ALLOWED):
                reason = f"Unsupported syntax {type(node).__name__}"
            elif isinstance(node, ast.Import) and (
                not self.config.allow_math or len(node.names) != 1 or node.names[0].name != "math"
            ):
                reason = "Only the pure math proxy can be imported"
            elif isinstance(node, ast.FunctionDef):
                if node.name != "decide" and not self.config.allow_helpers:
                    reason = "Helper functions disabled in this profile"
                elif (
                    node.decorator_list
                    or node.args.vararg
                    or node.args.kwarg
                    or node.args.kwonlyargs
                    or node.args.posonlyargs
                ):
                    reason = "Decorators and variadic/keyword-only parameters unsupported"
            if reason:
                raise SandboxError(f"Line {getattr(node, 'lineno', 1)}: {reason}")
        entry = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == "decide"]
        if len(entry) != 1 or len(entry[0].args.args) != 1:
            raise SandboxError("Define exactly one module-level decide(view) function")
        return tree

    def validate(self, code):
        """Parse without executing; normalized hashes ignore comments/formatting."""
        tree = self.parse(code)
        return {"ast_hash": hashlib.sha256(ast.dump(tree).encode()).hexdigest()}

    async def execute(self, code, policy_view, timeout_s=5.0):
        interpreter = _Interpreter(self, timeout_s)
        try:
            value = interpreter.run(code, policy_view.to_dict())
            if type(value) is not dict or set(value) - {"expand", "stop", "parallelism"}:
                raise SandboxError("Expected a decision dictionary")
            if type(value.get("expand")) is not list:
                raise SandboxError("expand must be a list")
            if any(type(item) is not str for item in value["expand"]):
                raise SandboxError("Expansion IDs must be strings")
            if type(value.get("stop", False)) is not bool:
                raise SandboxError("stop must be boolean")
            workers = value.get("parallelism")
            if workers is not None and (type(workers) is not int or workers < 1):
                raise SandboxError("parallelism must be a positive integer")
            return PolicyDecision(**value)
        except SandboxError as exc:
            line = getattr(interpreter.last_node, "lineno", None)
            if line and not str(exc).startswith("Line "):
                raise SandboxError(f"Line {line}: {exc}") from exc
            raise
        except Exception as exc:
            line = getattr(interpreter.last_node, "lineno", 1)
            raise SandboxError(f"Line {line}: {type(exc).__name__}: {exc}") from exc


class _Interpreter:
    def __init__(self, limits, timeout):
        if not math.isfinite(timeout) or timeout <= 0:
            raise SandboxError("A positive finite timeout is required")
        self.limits = limits
        self.deadline = time.monotonic() + timeout
        self.steps = self.units = 0
        self.env = {}
        self.functions = {}
        self.constants = {}
        self.call_depth = 0
        self.math_alias = "math"
        self.last_node = None

    def tick(self):
        self.steps += 1
        if self.steps > self.limits.max_steps or time.monotonic() > self.deadline:
            raise SandboxError("Policy operation/time limit exceeded")

    def checked(self, value: Any, depth=0) -> Any:
        self.tick()
        if depth > self.limits.max_value_depth:
            raise SandboxError("Value nesting limit exceeded")
        kind = type(value)
        size = len(value) if kind in (str, list, dict) else 1
        self.units += size + 1
        if size > self.limits.max_items or self.units > self.limits.max_units:
            raise SandboxError("Policy value allocation limit exceeded")
        if kind is int and value.bit_length() > self.limits.max_integer_bits:
            raise SandboxError("Integer size limit exceeded")
        if kind is float and not math.isfinite(value):
            raise SandboxError("Non-finite policy number")
        if kind is tuple:
            value, kind = list(value), list
        if kind is list:
            return [self.checked(item, depth + 1) for item in value]
        if kind is dict:
            if any(type(key) is not str for key in value):
                raise SandboxError("Only string dictionary keys are allowed")
            return {
                self.checked(k, depth + 1): self.checked(v, depth + 1) for k, v in value.items()
            }
        if kind not in (str, int, float, bool, type(None)):
            raise SandboxError("Only JSON values are available to policies")
        return value

    def run(self, code, view):
        if type(code) is not str or len(code.encode()) > self.limits.max_source_bytes:
            raise SandboxError("Policy source limit exceeded")
        tree = self.limits.parse(code)
        for node in tree.body:
            self.last_node = node
            if isinstance(node, ast.Import):
                if (
                    not self.limits.allow_math
                    or len(node.names) != 1
                    or node.names[0].name != "math"
                ):
                    raise SandboxError("Only the pure math proxy can be imported")
                self.math_alias = node.names[0].asname or "math"
            elif isinstance(node, ast.FunctionDef):
                if (
                    node.decorator_list
                    or node.args.vararg
                    or node.args.kwarg
                    or node.args.kwonlyargs
                    or node.args.posonlyargs
                ):
                    raise SandboxError(
                        "Decorators and variadic/keyword-only parameters unsupported"
                    )
                if node.name in self.functions or node.name in _FUNCTIONS:
                    raise SandboxError("Duplicate or reserved function name")
                self.functions[node.name] = (node, None)
            elif isinstance(node, ast.Assign):
                self.block([node])
                self.constants = dict(self.env)
            elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
                pass  # module docstring
            else:
                raise SandboxError("Only functions, constants and math imports at module level")
        if not self.limits.allow_helpers and set(self.functions) != {"decide"}:
            raise SandboxError("Helper functions disabled in this profile")
        if "decide" not in self.functions:
            raise SandboxError("Missing decide(view)")
        return self.checked(self.call_function("decide", [self.checked(view)], {}))

    def call_function(self, name, args, keywords):
        self.tick()
        self.call_depth += 1
        if self.call_depth > self.limits.max_call_depth:
            raise SandboxError("Function call depth exceeded")
        fn, closure = self.functions[name]
        names = [arg.arg for arg in fn.args.args]
        if len(args) > len(names) or set(keywords) - set(names):
            raise SandboxError("Invalid function arguments")
        bound = dict(zip(names, args, strict=False))
        if set(bound) & set(keywords):
            raise SandboxError("Duplicate function argument")
        bound.update(keywords)
        defaults = dict(
            zip(names[len(names) - len(fn.args.defaults) :], fn.args.defaults, strict=True)
        )
        for item in names:
            if item not in bound:
                if item not in defaults:
                    raise SandboxError("Missing function argument")
                bound[item] = self.expr(defaults[item])
        previous = self.env
        previous_functions = dict(self.functions)
        previous_math = self.math_alias
        self.env = {**(self.constants if closure is None else closure), **bound}
        try:
            self.block(fn.body)
        except _Return as result:
            return result.value
        finally:
            self.env = previous
            self.functions = previous_functions
            self.math_alias = previous_math
            self.call_depth -= 1
        return None

    def assign(self, target, value):
        value = self.checked(value)
        if isinstance(target, ast.Name):
            self.env[target.id] = value
        elif isinstance(target, (ast.Tuple, ast.List)):
            if len(target.elts) != len(value):
                raise SandboxError("Unpacking length mismatch")
            for item, part in zip(target.elts, value, strict=True):
                self.assign(item, part)
        elif isinstance(target, ast.Subscript):
            container, key = self.expr(target.value), self.expr(target.slice)
            if type(container) not in (dict, list):
                raise SandboxError("Assignment requires list or dictionary")
            container[key] = value
            self.checked(container)
        else:
            raise SandboxError("Unsupported assignment target")

    def block(self, body):
        for node in body:
            self.last_node = node
            self.tick()
            if isinstance(node, ast.Return):
                raise _Return(self.expr(node.value) if node.value is not None else None)
            if isinstance(node, ast.Import):
                self.math_alias = node.names[0].asname or "math"
            elif isinstance(node, ast.FunctionDef):
                if not self.limits.allow_helpers or node.name in _FUNCTIONS:
                    raise SandboxError("Helper disabled or reserved function name")
                self.functions[node.name] = (node, self.env)
            elif isinstance(node, ast.Assign):
                value = self.expr(node.value)
                for target in node.targets:
                    self.assign(target, value)
            elif isinstance(node, ast.AugAssign):
                value = self.expr(ast.BinOp(left=node.target, op=node.op, right=node.value))
                self.assign(node.target, value)
            elif isinstance(node, ast.If):
                self.block(node.body if self.expr(node.test) else node.orelse)
            elif isinstance(node, (ast.For, ast.While)):
                if node.orelse:
                    raise SandboxError("Loop else is unsupported")
                if isinstance(node, ast.For):
                    iterable = self.expr(node.iter)
                    if type(iterable) not in (list, dict, str):
                        raise SandboxError("Invalid iterable")
                    iterator = iter(iterable)
                    target_node = node.target
                else:
                    iterator = iter(())
                    target_node = ast.Name(id="_")
                while True:
                    self.tick()
                    if isinstance(node, ast.For):
                        try:
                            self.assign(target_node, next(iterator))
                        except StopIteration:
                            break
                    elif not self.expr(node.test):
                        break
                    try:
                        self.block(node.body)
                    except _Break:
                        break
                    except _Continue:
                        continue
            elif isinstance(node, ast.Break):
                raise _Break()
            elif isinstance(node, ast.Continue):
                raise _Continue()
            elif isinstance(node, ast.Expr):
                self.expr(node.value)
            elif not isinstance(node, ast.Pass):
                raise SandboxError("Unsupported statement")

    def expr(self, node):
        self.last_node = node
        self.tick()
        if isinstance(node, ast.Constant):
            return self.checked(node.value)
        if isinstance(node, ast.Name):
            return self.env[node.id]
        if isinstance(node, (ast.List, ast.Tuple)):
            return self.checked([self.expr(item) for item in node.elts])
        if isinstance(node, ast.Dict):
            return self.checked(
                {self.expr(k): self.expr(v) for k, v in zip(node.keys, node.values, strict=True)}
            )
        if isinstance(node, ast.Subscript):
            value = self.expr(node.value)
            if isinstance(node.slice, ast.Slice):
                part = node.slice
                key = slice(
                    *(
                        self.expr(x) if x is not None else None
                        for x in (part.lower, part.upper, part.step)
                    )
                )
            else:
                key = self.expr(node.slice)
            return value[key]
        if isinstance(node, ast.BinOp):
            left, right = self.expr(node.left), self.expr(node.right)
            if type(left) in (str, list) or type(right) in (str, list):
                if isinstance(node.op, ast.Mult):
                    seq, count = (left, right) if type(left) in (str, list) else (right, left)
                    if type(count) is not int or len(seq) * max(0, count) > self.limits.max_items:
                        raise SandboxError("Sequence multiplication limit exceeded")
                elif not (isinstance(node.op, ast.Add) and type(left) is type(right)):
                    raise SandboxError("Only sequence concatenation/repetition is supported")
            return self.checked(_BINARY[type(node.op)](left, right))
        if isinstance(node, ast.UnaryOp):
            value = self.expr(node.operand)
            return self.checked(
                {ast.Not: operator.not_, ast.USub: operator.neg, ast.UAdd: operator.pos}[
                    type(node.op)
                ](value)
            )
        if isinstance(node, ast.BoolOp):
            result = self.expr(node.values[0])
            for item in node.values[1:]:
                if (
                    isinstance(node.op, ast.And)
                    and not result
                    or isinstance(node.op, ast.Or)
                    and result
                ):
                    break
                result = self.expr(item)
            return result
        if isinstance(node, ast.Compare):
            left = self.expr(node.left)
            for operation, other in zip(node.ops, node.comparators, strict=True):
                right = self.expr(other)
                if not _COMPARE[type(operation)](left, right):
                    return False
                left = right
            return True
        if isinstance(node, ast.IfExp):
            return self.expr(node.body if self.expr(node.test) else node.orelse)
        if isinstance(node, (ast.ListComp, ast.DictComp, ast.GeneratorExp)):
            if not self.limits.allow_comprehensions:
                raise SandboxError("Comprehensions disabled")
            result: Any = {} if isinstance(node, ast.DictComp) else []
            previous = dict(self.env)

            def walk(index):
                self.tick()
                if index == len(node.generators):
                    if isinstance(node, ast.DictComp):
                        result[self.expr(node.key)] = self.expr(node.value)
                    else:
                        result.append(self.expr(node.elt))
                    self.checked(result)
                    return
                generator = node.generators[index]
                if generator.is_async:
                    raise SandboxError("Async comprehensions unsupported")
                for item in self.expr(generator.iter):
                    self.assign(generator.target, item)
                    if all(self.expr(test) for test in generator.ifs):
                        walk(index + 1)

            try:
                walk(0)
                return self.checked(result)
            finally:
                self.env = previous
        if isinstance(node, ast.Attribute):
            if (
                isinstance(node.value, ast.Name)
                and node.value.id == self.math_alias
                and self.limits.allow_math
                and node.attr in ("pi", "e", "tau")
                and node.attr in self.limits.enabled_math
            ):
                return getattr(math, node.attr)
            raise SandboxError("Arbitrary attribute access is not allowed")
        if isinstance(node, ast.Call):
            return self.call(node)
        raise SandboxError(
            f"Unsupported expression {type(node).__name__}; "
            "lambdas are supported only as sorting/selection keys"
        )

    def key_function(self, node, value) -> Any:
        if isinstance(node, ast.Name) and node.id in self.functions:
            return self.call_function(node.id, [value], {})
        if isinstance(node, ast.Lambda) and len(node.args.args) == 1:
            previous = self.env
            self.env = {**self.env, node.args.args[0].arg: value}
            try:
                return self.expr(node.body)
            finally:
                self.env = previous
        raise SandboxError("Sort key must be a one-argument lambda or helper")

    def call(self, node):
        args = [self.expr(arg) for arg in node.args]
        keyword_nodes = {item.arg: item.value for item in node.keywords}
        if None in keyword_nodes or len(keyword_nodes) != len(node.keywords):
            raise SandboxError("Keyword expansion/duplicates unsupported")
        keywords = {
            name: self.expr(value) for name, value in keyword_nodes.items() if name != "key"
        }
        if isinstance(node.func, ast.Attribute):
            attr = node.func.attr
            if (
                isinstance(node.func.value, ast.Name)
                and node.func.value.id == self.math_alias
                and self.limits.allow_math
            ):
                if attr not in _MATH or attr not in self.limits.enabled_math or keywords:
                    raise SandboxError(f"Unsupported or disabled math function: {attr}")
                return self.checked(_MATH[attr](*args))
            if not self.limits.allow_methods:
                raise SandboxError("Collection methods disabled")
            value = self.expr(node.func.value)
            method_name = f"{type(value).__name__}.{attr}"
            if method_name in _METHOD_NAMES and method_name not in self.limits.enabled_methods:
                raise SandboxError(f"Collection method disabled: {method_name}")
            if type(value) is list and attr == "sort":
                if args or set(keyword_nodes) - {"key", "reverse"}:
                    raise SandboxError("sort accepts only key and reverse keyword arguments")
                reverse = keywords.get("reverse", False)
                if "key" in keyword_nodes:
                    decorated = [
                        (self.key_function(keyword_nodes["key"], item), item)
                        for item in list(value)
                    ]
                    self.checked(decorated)
                    result = [
                        item[1]
                        for item in sorted(decorated, key=lambda item: item[0], reverse=reverse)
                    ]
                else:
                    result = sorted(value, reverse=reverse)
                value[:] = self.checked(result)
                return None
            if attr.startswith("_"):
                raise SandboxError("Private attributes forbidden")
            methods = _METHODS
            if attr not in methods.get(type(value), set()) or keywords:
                raise SandboxError(
                    f"Unsupported collection method {type(value).__name__}.{attr}; "
                    f"allowed: {sorted(methods.get(type(value), set()))}; "
                    "method keyword arguments are unsupported. "
                    "Node IDs are strings; node summaries are dictionaries."
                )
            if attr in ("append", "extend"):
                if len(args) != 1:
                    raise SandboxError("Mutation needs one argument")
                addition = [args[0]] if attr == "append" else args[0]
                if type(addition) is not list:
                    raise SandboxError("extend needs a list")
                validated = self.checked(value + addition)
                value[:] = validated
                return None
            result = getattr(value, attr)(*args)
            if attr in ("keys", "values", "items"):
                result = list(result)
            return self.checked(result)
        if not isinstance(node.func, ast.Name):
            raise SandboxError("Only named functions or approved methods are supported")
        name = node.func.id
        if name in self.functions:
            if "key" in keyword_nodes:
                keywords["key"] = self.expr(keyword_nodes["key"])
            return self.call_function(name, args, keywords)
        if name not in _FUNCTIONS:
            raise SandboxError("Unknown function")
        if name not in self.limits.enabled_builtins:
            raise SandboxError(f"Builtin disabled: {name}")
        if name in ("sorted", "min", "max") and "key" in keyword_nodes:
            if len(args) != 1 or set(keywords) - {"reverse"}:
                raise SandboxError("Invalid keyed selection arguments")
            values = list(args[0])
            decorated = [
                (self.key_function(keyword_nodes["key"], value), i, value)
                for i, value in enumerate(values)
            ]
            self.checked(decorated)
            if name == "sorted":
                return self.checked(
                    [
                        item[2]
                        for item in sorted(
                            decorated,
                            key=lambda item: item[0],
                            reverse=keywords.get("reverse", False),
                        )
                    ]
                )
            chosen = (min if name == "min" else max)(decorated, key=lambda item: item[0])
            return self.checked(chosen[2])
        if keywords and not (name == "sorted" and set(keywords) <= {"reverse"}):
            raise SandboxError("Unsupported function keywords")
        if name == "range":
            result = range(*args)
            if len(result) > self.limits.max_items:
                raise SandboxError("Range limit exceeded")
            return self.checked(list(result))
        if name == "get":
            if len(args) not in (2, 3) or type(args[0]) is not dict:
                raise SandboxError("get expects dictionary, key and optional default")
            return args[0].get(args[1], args[2] if len(args) == 3 else None)
        function = {
            "len": len,
            "min": min,
            "max": max,
            "sum": sum,
            "abs": abs,
            "sorted": sorted,
            "enumerate": enumerate,
            "zip": zip,
            "list": list,
            "dict": dict,
            "reversed": reversed,
            "all": all,
            "any": any,
            "round": round,
            "int": int,
            "float": float,
            "bool": bool,
            "str": str,
        }[name]
        result = function(*args, **keywords)
        if name in ("enumerate", "zip", "reversed"):
            result = list(result)
        return self.checked(result)
