from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from dreamrsi.models.base import Run
    from dreamrsi.models.discovery import DiscoveryNode
    from dreamrsi.models.evaluation import Evaluation
    from dreamrsi.models.events import Event
    from dreamrsi.models.policy import PolicyVersion


@runtime_checkable
class Store(Protocol):
    """Protocol for the storage backend."""

    async def save_run(self, run: Run) -> None: ...
    async def get_run(self, run_id: str) -> Run | None: ...
    async def save_node(self, node: DiscoveryNode) -> None: ...
    async def get_node(self, node_id: str) -> DiscoveryNode | None: ...
    async def get_nodes_by_tree(self, tree_id: str) -> list[DiscoveryNode]: ...
    async def save_policy(self, policy: PolicyVersion) -> None: ...
    async def get_policy(self, policy_id: str) -> PolicyVersion | None: ...
    async def list_policies(self) -> list[PolicyVersion]: ...
    async def get_champion(self) -> PolicyVersion | None: ...
    async def save_event(self, event: Event) -> None: ...
    async def get_events(self, run_id: str | None = None, limit: int = 100) -> list[Event]: ...
    async def save_evaluation(self, evaluation: Evaluation) -> None: ...
    async def save_checkpoint(self, campaign_id: str, data: dict) -> None: ...
    async def get_checkpoint(self, campaign_id: str) -> dict | None: ...
    async def close(self) -> None: ...
